# docker-compose.prod.yaml
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx.prod
    
    ports:
      - 80:80
    
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/dist:/var/www/certbot:rw
    
    working_dir: /usr/share/nginx/html
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.prod
    
    expose:
      - "8000"
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - "3306"
  
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    expose:
      - "8000"
    volumes:
      - ./chromadb/data:/data
    command: ["run", "--host", "0.0.0.0", "--port", "8000", "--path", "/data"]