# docker-compose.dev.yaml
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx.dev
    
    ports:
      - 80:80
    
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/images:/usr/src/app/images
    
    working_dir: /usr/share/nginx/html
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    
    ports:
      - "8001:8000"
    
    volumes:
      - ./backend:/usr/src/app
    
    working_dir: /usr/src/app
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend    # ← ./frontend/ 생략
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  # ← named volume 사용
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./mysql/02_IBA_cocktails.sql:/docker-entrypoint-initdb.d/02_IBA_cocktails.sql
    ports:
      - "3307:3306"
  
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb/data:/data
    command: ["run", "--host", "0.0.0.0", "--port", "8000", "--path", "/data"]

volumes:
  frontend_node_modules: