# docker-compose.dev.yaml
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx.dev
    
    ports:
      - 80:80
    
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    
    working_dir: /usr/share/nginx/html
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    
    expose:
      - "8000"
    
    volumes:
      - ./backend:/usr/src/app
    
    working_dir: /usr/src/app
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"