# docker-compose.prod.yaml
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx.prod
    
    ports:
      - 80:80
    
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    
    working_dir: /usr/share/nginx/html